import { qaEmail } from './qa-identity';
import { expect, test } from '@playwright/test';

test('alta administrativa conserva sesión, maneja duplicados y sidebar tiene contraste', async ({ page, request }, info) => {
  const fixture = await (await request.get('/__qa')).json();
  expect(fixture.fixture).toBe('booklibrary-phase5');
  expect(fixture.databaseName).toMatch(/^booklibrary_ui_test_[a-f0-9]{32}$/);
  await page.goto('/auth/login');
  await page.getByRole('textbox', { name: 'Correo electrónico', exact: true }).fill(qaEmail('qa_admin'));
  await page.locator('input[name="password"]').fill('QaLocalOnly!2026');
  await page.getByRole('button', { name: 'Iniciar sesión', exact: false }).click();
  await expect(page).not.toHaveURL(/\/auth\//);
  await page.goto('/admin/users');
  await page.getByRole('button', { name: 'Agregar usuario', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Agregar usuario' });
  await dialog.getByLabel('Nombre visible', { exact: true }).fill('Cuenta creada en pruebas');
  const username = `created_${Date.now()}`;
  await dialog.getByLabel('Nombre de usuario', { exact: true }).fill(username);
  await dialog.getByLabel('Correo electrónico', { exact: true }).fill(`${username}@example.test`);
  await dialog.getByLabel('Contraseña', { exact: true }).fill('StrongTest123!');
  await dialog.getByRole('button', { name: 'Crear usuario', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator('mat-snack-bar-container')).toContainText('Usuario creado correctamente.');
  await expect(page.getByRole('button', { name: `Editar usuario ${username}`, exact: true }).first()).toBeVisible();
  await expect(page).toHaveURL(/\/admin\/users/);
  await page.getByRole('button', { name: 'Agregar usuario', exact: true }).click();
  await dialog.getByLabel('Nombre visible', { exact: true }).fill('Duplicado');
  await dialog.getByLabel('Nombre de usuario', { exact: true }).fill(username);
  await dialog.getByLabel('Correo electrónico', { exact: true }).fill(`${username}@example.test`);
  await dialog.getByLabel('Contraseña', { exact: true }).fill('StrongTest123!');
  await dialog.getByRole('button', { name: 'Crear usuario', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('ya está registrado');
  await expect(dialog.getByLabel('Nombre visible', { exact: true })).toHaveValue('Duplicado');
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await page.locator('mat-snack-bar-container').getByRole('button', { name: 'Cerrar', exact: true }).click();
  const collapse = page.getByRole('button', { name: 'Contraer navegación', exact: true });
  if (await collapse.count()) await collapse.click();
  const icon = page.locator('.workspace__navigation a:not(.is-active) mat-icon').first();
  await expect(icon).toHaveCSS('color', 'rgb(89, 103, 128)');
  await expect(page.locator('.workspace__navigation a.is-active mat-icon')).toHaveCSS('color', 'rgb(255, 255, 255)');
  await expect(page.locator('.badge:not(.inactive)').first()).toHaveCSS('background-color', 'rgb(232, 247, 239)');
  await page.screenshot({ path: info.outputPath('admin-users-collapsed.png'), fullPage: true });
  await page.getByRole('button', { name: 'Agregar usuario', exact: true }).click();
  await page.addScriptTag({ path: require.resolve('axe-core/axe.min.js') });
  const violations = await page.evaluate(async () => (await (window as any).axe.run('[role="dialog"]', { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } })).violations.map((v: any) => ({ id: v.id, nodes: v.nodes.map((n: any) => n.failureSummary) })));
  expect(violations).toEqual([]);
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
  await page.screenshot({ path: info.outputPath('create-user-mobile.png'), fullPage: true });
});
